### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by patridge** [flatredball/TownRaiser-DesktopGL#5]
After the latest updates, there is a lot of missing text.

* Title screen below game logo
* Top of game stats
* In build menu details

![image](https://user-images.githubusercontent.com/713665/113440684-1c182580-93aa-11eb-95f4-d3be7854ee77.png)

**Comment by vchelaru** [comment]
Fixed.

**Comment by patridge** [comment]
Fixed via 178e7572638af22049a02328e8abe260d4bb70cd
